import Link from "next/link";

/**
 * Ownership/partnership disclosure shown wherever properties are listed.
 * RRWA doesn't own the underlying asset — this makes that unambiguous.
 */
export default function PartnershipNotice() {
  return (
    <div className="partnership-notice">
      <span className="partnership-notice-label">Partnership Notice</span>
      <p>
        RRWA does not own or claim ownership of the underlying property or
        asset. Each pool is created through a partnership with the verified
        asset owner. The underlying asset remains under the owner&apos;s
        ownership and management. Revenue generated by the asset is shared
        according to the partnership agreement, with the allocated portion
        distributed to pool participants as yield (APY).
      </p>
      <p>
        Want to partner with RRWA?{" "}
        <Link href="/list" className="btn" style={{ marginTop: 12 }}>
          List your property <span className="arr">→</span>
        </Link>
      </p>
    </div>
  );
}
